two_joints_controller:
  type: controller_ns/two_joints_controller
  joints: ['front_left_1_joint', 'front_left_2_joint']
  front_left_1_joint/pid: {p: 5.0, i: 5.0, d: 0.0}
  front_left_2_joint/pid: {p: 5.0, i: 5.0, d: 0.0}
